name: Unit test - PR
run-name: (PR - ${{ github.head_ref  }} -> ${{ github.base_ref  }} ) - Unit testing

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  pr-unit-testing:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test --file-reporter "json:tests/json"

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: tests/json